version: '3'
services:
  frontend:
    build: ./presentation_tier
    ports:
      - "3000:3000"
    environment:
      # - REACT_APP_API_URL=http://localhost:3001/api
      # - REACT_APP_API_URL=http://<EC2_PUBLIC_IP>:3001/api
      - REACT_APP_API_URL=${REACT_APP_API_URL}

    depends_on:
      - backend

  backend:
    build: ./application_tier_flask
    ports:
      - "3001:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}